// src/components/ResourceDisplay.tsx
import { useGameStore } from "../store/gameStore";
import resourcesData from "../data/resources.json";
import skillsData from "../data/skills.json";

export default function ResourceDisplay() {
  const { resources, skills } = useGameStore();

  // If resources/skills aren't initialized yet, show a loading placeholder
  if (!resources || !skills) return <p>Loading...</p>;

  return (
    <div style={{ padding: '20px' }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px' }}>
        {resourcesData.map((r) => {
          const type = r.id as keyof typeof resources;
          const skillsForResource = skillsData.filter(
            (g) => g.effects.generates && (g.effects.generates as any)[r.id]
          );

          return (
            <div key={type} style={{
              backgroundColor: '#2a2a2a',
              borderRadius: '8px',
              padding: '15px',
              border: '1px solid #444'
            }}>
              <div style={{ textAlign: 'center', marginBottom: '15px' }}>
                <span style={{ fontSize: '24px' }}>{r.emoji}</span>
                <h3 style={{ margin: '10px 0', color: 'white' }}>{r.name}</h3>
                <h4 style={{ margin: '5px 0', color: '#4CAF50' }}>{resources[type] ?? 0}</h4>
              </div>
              
              {skillsForResource.length > 0 && (
                <div>
                  <p style={{ color: '#ccc', marginBottom: '10px' }}>Generated by:</p>
                  {skillsForResource.map((g) => (
                    <div key={g.id} style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      padding: '5px 0',
                      borderBottom: '1px solid #444'
                    }}>
                      <span>{g.icon} {g.name}</span>
                      <span style={{ color: '#4CAF50' }}>Level {skills[g.id] ?? 0}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
